### ISSUE TITLE
Could not find two required image files for the game, plus screensize refresh error: Gamemaker studio 2

### ISSUE THREAD

**Issue by YalekW5435** [LDinos/bejeweled-1-clone#3]
Could not load the following file during the build:

![image](https://user-images.githubusercontent.com/23326973/102950390-89a5e300-4498-11eb-873b-917e57bbf475.png)

including this error:

![image](https://user-images.githubusercontent.com/23326973/102950487-c540ad00-4498-11eb-80d2-36990f7c90e8.png)

Also why would this game need to be ported to the *mobile* platform now...?  Thats the worst place to put it, suggest putting it on a PC instead since I dont like using smartphones to play games, neither tablets....

OS info in case if one needs it:
Lenovo H50-55
2TB HDD

AMD FX 870K (the worst processor in the world IMO)
AMD Radeon R7 350 (and yes, Subzero, this GPU can run dijeweled and modern PC software that doesnt require a LOT of pixels and resource usage lol).
Software used to open:

GameMaker Studio 2: IDE v 2.3.1.542, runtime v2.3.1.409.

Also Ldinos, Im gonna be attempting to make this game better, so please respect my wishes even if you consider them "bad".

**Comment by LDinos** [comment]
Had the same problem, will talk to Onekone about this build in gamemaker.
The PC version is already uploaded here https://github.com/LDinos/bejeweled-1-clone/releases
The reason I am making a mobile port is because there isn't one at the moment. You can play the real bejeweled in PC

**Comment by YalekW5435** [comment]
K.  Also, are we good to be "friends" on discord? :(, I also want to talk to onekone as well.
